language: node_js
node_js:
- '8'
install:
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zk"
  - git config user.email "itzhangke@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${github_token}@${GH_REF}" master:master

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/jacky-pro/blog.github.io.git
cache:
  directories:
  - node_modules